# Generated by Django 4.2.5 on 2023-10-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='наименование продукта')),
                ('description', models.CharField(max_length=100, verbose_name='фамилия')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='превью')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('description',),
            },
        ),
    ]
