# Generated by Django 4.2.5 on 2023-10-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_product_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='product_name',
            new_name='category',
        ),
    ]
