# Generated by Django 4.2.5 on 2023-10-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_product_name_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Наименование категории'),
        ),
    ]
